### ISSUE TITLE
Can I use this to develop maps ？

### ISSUE THREAD

**Issue by opencaw** [seven-mile/ScriptHookWar3#1]
Can I use this to develop maps？
I want to create objects through C + + implementation and dynamically execute jass code. I don't know whether it is feasible to implement it in C + +,
我可以用这个开发地图吗
我想通过c++实现创建物品 ，动态执行jass代码，用c++实现是否可行，我不是很懂这些，

**Comment by opencaw** [comment]
I want to implement it on version 1.27
我想在1.27版本上实现

**Comment by seven-mile** [comment]
Well, It's theoretically feasible on 1.27. Combined with the widely known "Memory hack", you can inject custom DLLs into WC3 and then do whatever you want with the SDK in this repo. But I have no plan to provide such support directly.
Moreover, this repo only support 1.20e & 1.24e for now. I haven't adapted it to 1.27's offset.
